const emptyItem = () => ({ month: '', day: '', name: '', specification: '', quantity: '', unitPrice: '', amount: '', tax: '', remark: '' });
const state = {
  step: 0, photo: '',
  supplierBusinessNumber: '', supplierName: '', supplierRepresentative: '', supplierPostalCode: '', supplierAddress: '', supplierBusinessType: '', supplierBusinessCategory: '', supplierEmail: '',
  recipientBusinessNumber: '', recipientName: '', recipientRepresentative: '', recipientPostalCode: '', recipientAddress: '', recipientBusinessType: '', recipientBusinessCategory: '', recipientEmail: '',
  issueDate: new Date().toISOString().slice(0, 10), invoiceRemark: '', cashAmount: '', checkAmount: '', noteAmount: '', accountsReceivable: '', claimType: '청구',
  items: Array.from({ length: 4 }, emptyItem)
};
const simpleFieldKeys = Object.keys(state).filter((key) => !['step', 'photo', 'items'].includes(key));
let stream;
const panel = document.querySelector('#panel'); const next = document.querySelector('#next'); const back = document.querySelector('#back');
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[character]); }
function field(label, key, placeholder = '', type = 'text') { return `<label>${label}<input id="${key}" type="${type}" placeholder="${placeholder}" value="${esc(state[key])}" /></label>`; }
function claimTypeField() { return `<label>이 금액을<select id="claimType"><option value="청구" ${state.claimType === '청구' ? 'selected' : ''}>청구</option><option value="영수" ${state.claimType === '영수' ? 'selected' : ''}>영수</option></select></label>`; }
function itemField(label, row, key, placeholder = '') { return `<label>${label}<input data-item-row="${row}" data-item-key="${key}" placeholder="${placeholder}" value="${esc(state.items[row][key])}" /></label>`; }
function partyFields(title, prefix) { return `<h2 class="form-heading">${title}</h2><div class="party-form">${field('사업자등록번호 *', `${prefix}BusinessNumber`, '예: 123-45-67890')}${field('상호 *', `${prefix}Name`, '회사 또는 가게 이름')}${field('대표자 성명', `${prefix}Representative`)}${field('이메일', `${prefix}Email`, 'example@company.kr')}${field('우편번호', `${prefix}PostalCode`)}${field('사업장 주소', `${prefix}Address`)}${field('업태', `${prefix}BusinessType`, '예: 도소매')}${field('종목', `${prefix}BusinessCategory`, '예: 전자상거래')}</div>`; }
function itemFields(row) { return `<section class="item-card"><h3>품목 ${row + 1}${row === 0 ? ' <small>(필수)</small>' : ' <small>(선택)</small>'}</h3><div class="party-form item-form">${itemField('품목', row, 'name', '예: 농산물 판매')}${itemField('공급가액 (부가세 제외)', row, 'amount', '예: 100000')}${itemField('거래 월', row, 'month', '예: 07')}${itemField('거래 일', row, 'day', '예: 18')}${itemField('규격', row, 'specification')}${itemField('수량', row, 'quantity')}${itemField('단가', row, 'unitPrice')}${itemField('세액', row, 'tax')}${itemField('품목 비고', row, 'remark')}</div></section>`; }
const panels = [
  () => `<h1>종이 세금계산서를 찍어 주세요</h1><p class="lead">계산서가 화면 안에 모두 들어오게 놓고, 밝은 곳에서 촬영해 주세요.</p><p class="writing-tip">🖊️ <strong>볼펜으로 글자를 또박또박 작성해 주세요.</strong><br /><span>글자, 사업자등록번호, 금액이 선명할수록 더 정확하게 읽을 수 있어요.</span></p><div class="camera-box"><video id="camera" autoplay muted playsinline></video><img id="photo-preview" class="hidden" alt="촬영한 세금계산서 미리보기" /></div><div class="capture-buttons"><button id="start-camera" class="secondary">카메라 켜기</button><button id="take-photo" disabled>사진 찍기</button><label class="file-button">사진 파일 고르기<input id="photo-file" type="file" accept="image/*" capture="environment" /></label></div><p class="tip">사진이 흔들렸다면 다시 찍어 주세요. 천천히 해도 괜찮아요.</p>`,
  () => `<h1>내용을 확인해 주세요</h1><p class="lead">Gemini가 읽은 값을 적용했습니다. 공급자와 공급받는 분 정보를 각각 확인·수정해 주세요.</p>${state.photo ? `<img class="receipt-thumb" src="${state.photo}" alt="촬영한 계산서" />` : ''}${partyFields('공급자 (나)', 'supplier')}${partyFields('공급받는 분 (거래처)', 'recipient')}<h2 class="form-heading">거래 내용</h2>${field('작성일 *', 'issueDate', '', 'date')}${state.items.map((_, row) => itemFields(row)).join('')}<h2 class="form-heading">추가 정보</h2><div class="party-form">${field('계산서 비고', 'invoiceRemark')}${field('현금', 'cashAmount')}${field('수표', 'checkAmount')}${field('어음', 'noteAmount')}${field('외상미수금', 'accountsReceivable')}${claimTypeField()}</div>`,
  () => { const used = state.items.filter((item) => item.name || item.amount); const total = used.reduce((sum, item) => sum + (Number(String(item.amount).replace(/,/g, '')) || 0), 0); return `<h1>자동 입력할 준비가 됐어요</h1><p class="lead">버튼을 누르면 <strong>estamp-helper.lovable.app</strong>이 열리고 아래 값으로 기본값을 덮어씁니다.</p><dl><dt>공급자</dt><dd>${esc(state.supplierName) || '-'} (${esc(state.supplierBusinessNumber) || '-'})</dd><dt>공급받는 분</dt><dd>${esc(state.recipientName) || '-'} (${esc(state.recipientBusinessNumber) || '-'})</dd><dt>품목</dt><dd>${used.length ? used.map((item) => esc(item.name) || '이름 없는 품목').join(', ') : '-'}</dd><dt>공급가액 합계</dt><dd>${total ? `${total.toLocaleString()}원` : '-'}</dd><dt>작성일</dt><dd>${esc(state.issueDate)}</dd></dl><div class="notice">인증서·로그인·발급 버튼은 사용하지 않습니다. 열린 대상 화면에서 내용을 검토한 뒤 발급 여부를 직접 결정해 주세요.</div>`; }
];
function showToast(message, error = false) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.className = error ? 'show error' : 'show'; setTimeout(() => toast.className = '', 6500); }
function saveInputs() { simpleFieldKeys.forEach((key) => { const element = document.querySelector(`#${key}`); if (element) state[key] = element.value.trim(); }); document.querySelectorAll('[data-item-row]').forEach((element) => { state.items[Number(element.dataset.itemRow)][element.dataset.itemKey] = element.value.trim(); }); }
function stopCamera() { stream?.getTracks().forEach((track) => track.stop()); stream = undefined; }
function valid() { saveInputs(); if (state.step === 0 && !state.photo) return '먼저 종이 세금계산서를 촬영하거나 사진 파일을 골라 주세요.'; const firstItem = state.items[0]; if (state.step === 1 && (!state.supplierBusinessNumber || !state.supplierName || !state.recipientBusinessNumber || !state.recipientName || !firstItem.name || !firstItem.amount)) return '공급자·공급받는 분의 사업자등록번호와 상호, 품목 1의 품목명과 공급가액은 꼭 확인해 주세요.'; }
async function recognizePhoto() { next.disabled = true; next.textContent = '정보를 읽는 중…'; const result = await window.taxAssist.recognizeInvoice(state.photo); if (result.ok) { Object.assign(state, result.fields); if (!Array.isArray(state.items)) state.items = Array.from({ length: 4 }, emptyItem); state.step = 1; render(); const count = result.fields.items?.filter((item) => item.name).length || 0; showToast(`${count || 1}개 품목을 포함한 내용을 확인 화면에 적용했어요.`); } else showToast(result.message, true); next.disabled = false; next.textContent = '다음으로'; }
async function setPhoto(dataUrl) { state.photo = dataUrl; const preview = document.querySelector('#photo-preview'); preview.src = dataUrl; preview.classList.remove('hidden'); document.querySelector('#camera').classList.add('hidden'); stopCamera(); await recognizePhoto(); }
function bindCamera() { document.querySelector('#start-camera').onclick = async () => { try { stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); const video = document.querySelector('#camera'); video.srcObject = stream; video.classList.remove('hidden'); document.querySelector('#take-photo').disabled = false; } catch { showToast('카메라를 사용할 수 없어요. 사진 파일을 골라 주세요.', true); } }; document.querySelector('#take-photo').onclick = () => { const video = document.querySelector('#camera'); const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d').drawImage(video, 0, 0); setPhoto(canvas.toDataURL('image/jpeg', 0.9)); }; document.querySelector('#photo-file').onchange = (event) => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setPhoto(reader.result); reader.readAsDataURL(file); }; }
function render() { stopCamera(); panel.innerHTML = panels[state.step](); document.querySelectorAll('#steps li').forEach((element, index) => element.className = index === state.step ? 'active' : index < state.step ? 'done' : ''); document.querySelector('#progress').textContent = `${state.step + 1} / 3 단계`; const progressFill = document.querySelector('#progress-fill'); if (progressFill) progressFill.style.width = `${((state.step + 1) / 3) * 100}%`; back.style.visibility = state.step ? 'visible' : 'hidden'; next.textContent = state.step === 2 ? '모의 홈택스에 자동 입력하기' : '다음으로'; if (state.step === 0) bindCamera(); }
next.onclick = async () => { const error = valid(); if (error) return showToast(error, true); if (state.step < 2) { state.step += 1; render(); } else { next.disabled = true; next.textContent = '대상 화면에 입력 중…'; const result = await window.taxAssist.issueInvoice(state); showToast(result.message, !result.ok); next.disabled = false; next.textContent = '모의 홈택스에 자동 입력하기'; } };
back.onclick = () => { saveInputs(); if (state.step) { state.step -= 1; render(); } };
render();
